### ISSUE TITLE
Progress styles not available

### ISSUE THREAD

**Issue by filoxo** [sebald/spectacle-theme-nova#8]
[spectacle-scripts](https://github.com/FormidableLabs/spectacle-scripts) seems to be the new way of starting a Spectacle presentation now. This theme doesn't seem to work, I just get the following error related to `progress.bar`: 

<img width="632" alt="screen shot 2017-09-11 at 2 37 22 pm" src="https://user-images.githubusercontent.com/4202993/30295712-ceb8546e-96fe-11e7-8648-e8c8f02c5087.png">

**Comment by filoxo** [comment]
Hmm my initial assessment was wrong. Seems to be an issue with progress bar styles. If I disable the progress bar in my presentation (`<Deck ... theme={theme} progress="none">`), everything seems to work.

**Comment by filoxo** [comment]
Well, now I just feel silly. There aren't any progress styles included, therefore they're undefined as the error shows above. I'll probably submit a PR to add. Sorry about the bad issue report!

**Comment by sebald** [comment]
Closing this, since it's resolved and there will be some styles when #9 is merged.
